# Site settings
author: Allison Ricker
title: Alli Ricker
header-img: img/home-bg.png
email: alliricker@gmail.com
copyright_name: Allison Ricker
description: > # this means to ignore newlines until "baseurl:"
  Software Engineering Flex
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alliricker

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
